In [59]:
num_1=4
num_2=2
print(num_1+num_2)

6

In [60]:
tup_1=(1,2,3)
tup_2=(1,1,1)
print(tup_1+tup_2) #operação considera objeto inteiro pra tupla e lista (add ao final, concatena)

#mesma coisa da conta acima:
tup_1+=tup_2

(1, 2, 3, 1, 1, 1)

In [61]:
#para converter obj em lista, mas tup_1 ainda é uma tupla, só 
listtup=list(tup_1)
print(listtup)

listtup[2]+=2 #a cada vez que roda a célula, vai fazer a operação (se fizer fora da celula onde ta instanciando)
listtup

[1, 2, 3, 1, 1, 1]

[1, 2, 5, 1, 1, 1]

In [62]:
listtup+=tup_1
listtup

[1, 2, 5, 1, 1, 1, 1, 2, 3, 1, 1, 1]

In [63]:
#lista e tupla faz indexação automática e em ordem, então dá pra fazer as operações
#dicionário tem indexação manual, nao tem uma ordem
dic1={'a':1,'b':2,'c':3}
dic2={'aa':10,'bb':20}
print(dic1,dic2)

{'a': 1, 'b': 2, 'c': 3} {'aa': 10, 'bb': 20}

In [64]:
#para concatenar dicionarios:
dic1.update(dic2)
dic1

{'a': 1, 'b': 2, 'c': 3, 'aa': 10, 'bb': 20}

In [65]:
import numpy as np

In [66]:
array=np.array(listtup)
array

array([1, 2, 5, 1, 1, 1, 1, 2, 3, 1, 1, 1])

In [67]:
array[2]+=2
array

array([1, 2, 7, 1, 1, 1, 1, 2, 3, 1, 1, 1])

In [68]:
array*=2
array

array([ 2,  4, 14,  2,  2,  2,  2,  4,  6,  2,  2,  2])

Lista e tupla se somar, vai olhar o obj inteiro e concatenar. 
Pra somar elemento por elemento, precisa indexar > da pra usar estrutura de repetição

Array se somar, vai somar a cada elemento
Para concatenar usa .concat

In [69]:
#inserir elemento na ultima posição > nao instanciei obj aqui
np.insert(arr=array, obj=0, values=[1,1,2])

array([ 1,  1,  2,  2,  4, 14,  2,  2,  2,  2,  4,  6,  2,  2,  2])

In [70]:
array.shape

(12,)

In [72]:
array.reshape(2,6)

array([[ 2,  4, 14,  2,  2,  2],
       [ 2,  4,  6,  2,  2,  2]])

In [78]:
#se eu quiser 6 linhas e nao importa quantas colunas:
arr2=array.reshape(4,-1)
arr2

array([[ 2,  4, 14],
       [ 2,  2,  2],
       [ 2,  4,  6],
       [ 2,  2,  2]])

In [ ]:
import pandas as pd

In [79]:
df=pd.DataFrame(arr2)
df

   0  1   2
0  2  4  14
1  2  2   2
2  2  4   6
3  2  2   2

In [ ]:
#da pra alterar valor especifico
#tbm existe zeros_like
arr_ones=np.ones_like(df)
arr_ones[1,1]=222
arr_ones

array([[  1,   1,   1],
       [  1, 222,   1],
       [  1,   1,   1],
       [  1,   1,   1]])

In [ ]:
#0 é f e 1 é v, funciona pra int e float
0==False

True

In [83]:
1<=3==3

True

In [85]:
# metodos values, items, keys (obj.metodo())
#dicionario nao compara maior/menor, mas se pedir comom items ele retorna como tupla, ai dá
{'a':1,'b':2}.items() <= {'a':1,'b':2}.items()

True

In [92]:
#aleatorio com media 0 e dp 1 > terá 10 valores entre -1 e 1 com dist normal
#PRIMEIRO TESTA SE O QUE QUERO FAZER FUNCIONA E DEPOIS QUE DER, INSTANCIO O OBJ PRA ECONOMIZAR RAM
arr_rand=np.random.normal(0,1,1000).reshape(-1,10)
print(arr_rand)
arr_rand[:2]

[[ 0.99949988  1.48059584 -1.02451155 -0.8614114  -0.27996923 -2.85507207
   0.1047417   1.1344126  -0.31293796 -0.34346681]
 [-1.20196757 -0.02035361 -0.5311331  -0.22103344 -0.41925933  0.89302975
   0.90020952  0.27964719  0.26177091 -0.67754126]
 [ 0.18850497  1.10443981  2.42578467  1.18177855  0.72258208 -1.23878656
   0.70823512  1.92554111 -1.33021764  1.93347407]
 [ 0.67589444 -1.0017361  -0.44258861  0.19743198 -0.4752975  -0.33669858
  -0.51576935 -0.31478928  1.44281144 -1.02488619]
 [ 0.35438948 -0.41689013 -0.48146264  1.38567486  0.0464263   1.56710423
  -0.43107437 -2.19146306  1.20272403  0.79190185]
 [-1.02028428 -0.123975   -1.05368366  1.22507746  0.86598407  0.8042167
  -1.31321378 -0.28391815  0.2826682   0.13849776]
 [-1.09984609 -1.14965536 -0.82276621 -0.03398387 -0.15932609 -1.67536257
   1.52346367 -0.34952536  0.31778961  1.62427615]
 [-1.30231636  0.37481315 -0.30063741 -0.75139999 -0.66686957  0.45218098
  -0.35100422 -0.26706457 -1.59587904  1.29782654]
 [ 0.54224716  0.42405921 -0.10975427  1.03960808  1.17702397 -0.69369783
   0.36100499  0.76026468 -1.38580415 -1.42359006]
 [ 1.36901718 -1.09094006 -0.3456264  -1.9963791   0.77294515 -1.80235396
   0.25883212  0.58643208 -0.72666504 -0.12589706]
 [ 0.76242004  1.1861365  -0.77165319 -1.52665524 -2.2641329   0.56232712
   0.36569073 -1.11468384  0.98286743  0.25933538]
 [ 0.69276695  0.65586227  1.58204461  1.12816707  0.06467159 -0.14066148
  -0.37374362 -0.78697243  0.62521835 -0.32489313]
 [-1.35686405 -0.23606121  0.38309204  1.26789215  1.64982404 -0.44839977
   0.2757708  -1.5296925   0.28083022  1.45234311]
 [ 1.14271381  1.00760838  0.87599779 -0.45584058  0.75059795  0.32514368
   0.25744682  0.3653333  -0.22654623  0.34234924]
 [ 0.66769091  1.1095136   1.41712561 -0.43542609  0.56494546  0.6502336
   1.44500188 -0.44313219  0.19642736 -1.21940404]
 [-0.25311103 -0.10436642  0.76817791 -0.64871947  0.78025826 -1.48813812
  -0.94852425 -1.90699605  2.40895444  0.3700748 ]
 [-0.79377979 -1.18697486 -0.32522984  0.35604609  0.75988772 -1.3274007
   1.05052639  2.0137046  -0.14201496  0.64833934]
 [ 0.38287863 -0.18261254  1.3612919  -0.93280454  0.04569622  0.43584714
   1.99257559 -1.23775006 -0.07153309 -0.39013646]
 [ 0.66306795 -1.49726757  0.63337927  0.39550768 -1.73790026 -0.05000364
  -1.11812948 -0.85047673  0.99466381  1.04901836]
 [ 0.59632282  0.4928992   0.06694955  0.23097752  0.69887886  0.16866844
   0.04221188 -0.97422958  0.11547226  1.32921497]
 [ 0.09638719  1.89160706 -0.10569068 -0.59371795 -1.44309356  1.3820957
  -1.32861551  0.17516928 -0.23047605 -1.31735412]
 [ 0.15828785 -0.44056973 -1.45431109  0.19747718 -0.21306969 -1.08504896
  -0.47463138  0.3508997   2.14522854 -0.00888978]
 [ 0.39354055 -0.06728783 -0.85149582  0.25010722 -0.15039107  1.00535297
  -1.00614932 -1.32921482 -1.39275526 -0.00390953]
 [-1.27887132  1.03289702 -0.52023843 -1.35267213  0.3429855   0.8991931
   0.50007201  0.23981656 -0.48260178  0.63874922]
 [-1.18724427  1.45085525  0.5770954   1.05259685  0.97882063 -0.79011317
   0.49171153 -0.23338509 -1.06369004  0.62603423]
 [-0.16841515  0.60107457  0.62356464 -0.59042227 -0.65589162  0.58882203
  -0.66887208  0.03059825  0.39439087  0.59413967]
 [ 1.25142843  0.86446948  0.4515709  -0.53711626  1.35908119  0.23038115
  -0.3375554   0.35906496  0.41352499  1.06035138]
 [-0.8746319  -1.4737358   1.39330986  1.60967141  0.31790998 -0.48419939
  -0.52736431 -1.58455631 -1.30883611  0.98704899]
 [-0.64966646 -1.79233154  1.30538934  1.23804802  0.1534898  -0.4443215
  -0.61403076  2.36462133 -0.93619903  0.76534829]
 [ 0.16325529  0.17318383  0.50879566 -2.09376696  0.06823155  0.70928115
   1.26856811 -1.79222768 -0.49030799  0.4723335 ]
 [ 0.18511329 -0.66855141  0.05579447  0.89229562  0.03543619 -0.43766012
  -0.71160018 -0.26316977 -1.00069002  0.03098563]
 [-1.63533302  0.32439816  0.61716075  1.81972962 -0.80269364  0.57430113
   1.205238    1.08134765  0.99556304 -0.66645278]
 [-0.20495813 -0.50723069  1.75330519  0.13735877 -1.20324814  1.91063226
   0.30832395  0.01993541  1.67533693  0.82388642]
 [ 1.26140848  0.84353002  0.85213224  0.27028259 -0.82793711 -1.9998339
  -1.16625928 -0.75368653  0.0676076   0.66474076]
 [-0.43750951  0.29409685  0.49590504 -0.30508098  1.63986923  1.22444979
  -0.64646714  1.08831832  0.67178882 -0.18201435]
 [ 1.01913183 -0.17347311 -0.72994903 -0.46342935  1.05452401 -0.43317874
   1.29126789 -2.11688283  0.88989261  2.3484089 ]
 [ 0.05115359  0.27464278  0.62544453  0.14728477  1.65153258 -0.35631618
   1.23312607  0.05501079  0.43984816 -1.248866  ]
 [-0.6100323  -1.05457458  1.1840159   1.17834054  0.76124056 -0.15061852
   0.68893146 -0.8666303  -1.40807346 -0.3970587 ]
 [-0.32334977  0.19144765 -1.66216661 -0.23066752  0.4906839   1.25750363
  -1.05482544  1.04205712  0.06274944 -1.51683716]
 [ 1.52905423  0.24428526  0.78505044 -0.4266151  -0.58358067 -1.41653498
   0.15921271  0.63636883 -0.67600638 -0.16183153]
 [ 0.79244046 -1.52360147 -0.66349819 -1.50149939 -0.9845804   1.36966773
  -1.41243547  2.56506078 -1.30923654  0.43858203]
 [ 0.73016062  0.54598225 -0.26985062 -1.01799954  0.61967822 -1.20391084
  -1.87695756 -0.99534987 -0.61327708 -1.48426521]
 [-0.03500735  0.33860718 -0.96563518  0.30600522  0.59567979 -0.11734245
  -0.68432969 -0.03029953 -1.15823156  1.46427524]
 [-0.64380129  0.11353719  1.44013219  0.25729397 -1.17660427 -0.07983465
  -0.08267336 -0.0341326  -0.32415213 -0.69241461]
 [-1.58103737 -0.25146548 -2.52602113 -0.59392872 -0.70542617 -0.06610155
  -0.41266415  0.04669349 -0.94385772 -0.32568019]
 [ 0.79431392  1.48034159  0.29048864  0.2316384   0.74062516  0.31724704
   0.07530893 -0.59642533 -0.20952073 -0.43181768]
 [ 1.94646628 -0.69938199 -0.05300253 -0.06734616  1.05360463  0.67924167
  -0.0138697  -0.3930431   1.31351841  0.52274368]
 [-0.08957781 -0.47318923  0.9948506   0.52031087  0.66844507 -1.59006777
  -0.26809685  0.10923849  1.87361271  1.00696726]
 [ 1.60154468 -0.41187644  1.16137086 -0.0914514  -0.24969593 -0.82130972
   0.28589308 -0.10674344 -0.22398123  1.05842031]
 [ 0.5469591  -0.34508418  0.87978072 -0.48222963  1.31359079 -2.38826677
   1.97929885 -0.31345204 -0.28301447  0.68789513]
 [-0.17003245 -1.50488925 -1.85228605  0.83727135 -0.86396692  0.85531407
   1.2622336   0.84265799 -0.35495485 -0.05673273]
 [ 0.91669358  0.10566774  0.62179589 -1.52369523 -1.08278713 -0.83345191
   0.4373613   1.04698572 -1.06627164 -0.00380404]
 [ 0.70481235  1.10935675  0.00998406  0.58993391  1.90017735 -0.65613863
  -1.25582729 -0.33032572 -0.65515368 -1.64018938]
 [ 0.10256929 -0.70008138  0.20085856  0.57775068 -0.14769865 -1.2208442
   0.46136857  0.51144177  1.41711435 -1.1033433 ]
 [ 1.63994381 -1.56994169 -0.54039203  0.81198217 -0.46946056 -0.16141017
   0.5885107  -1.06106272 -0.66416178  0.65571571]
 [-0.71886151  1.43805766 -0.07487929  0.16039863  1.34178101  0.5804722
  -0.82060288 -0.78786546 -1.41377503  0.11989566]
 [-0.5331716  -1.55011442 -0.7718125  -0.4612956  -0.12188356 -0.6804313
   0.54491464 -1.16379723 -0.0837303   0.18758127]
 [ 0.6518781  -0.76934749  0.77674901 -0.70856574 -0.91023743  1.00018559
  -0.54458831 -0.45709042 -2.49125404 -1.9113343 ]
 [ 1.0662089   0.93422468 -1.55478218  1.59950559  0.54459214  0.1278232
  -0.39964858  1.1407071  -0.44425559  1.19939407]
 [ 0.46437959 -0.68816357 -1.33720273  0.33209896 -1.19986297  0.67533885
   0.00758225  1.27199285  0.36069649 -1.88150643]
 [-0.29648209 -0.46951691 -0.23270722 -1.84652732  0.43834271  0.09502811
   0.94165388 -0.189043    1.68719788  0.84081524]
 [-0.63021295 -1.74074771  0.43758461  0.5387164  -0.10860408 -0.67192673
   0.15720161 -0.83874188  0.62878062 -0.02795825]
 [ 0.17682147 -0.45867639 -2.01060801  0.12083167  0.89375531 -1.19354698
   0.15756553  0.57517279  0.41403984  1.49113983]
 [-1.46664666  0.09086612 -0.62028806 -0.02218746 -1.79904228 -0.27119347
  -0.68093336  1.88142992 -0.55531078 -0.59707833]
 [ 0.33307222 -0.51048161 -0.10886087 -0.88204912  0.11996482  0.4685581
   0.00415998  0.35185298  0.80725432 -0.07387946]
 [ 0.67355799  0.55076638 -0.80256574  0.50792968  0.45592238  0.30631642
   0.50253847  0.73431509  0.62441756  0.24859263]
 [-0.0943703  -0.93023309 -0.8328169  -0.49346944  0.05882649  0.10148387
  -0.3112985   2.10732113 -0.09209899 -1.86292427]
 [ 1.38864317 -0.79131277  0.62878448  0.31284394 -0.63828122  1.00727998
   0.20697529  2.24697873 -0.2634297   0.40329788]
 [-0.78039443  1.32165857 -0.72062083 -0.93240303  1.0045729   0.8737434
   0.43509017  1.36797763  0.72945871  0.63163183]
 [ 1.28259336 -1.42420661  1.46344657  0.50451002  0.08538257 -0.34587413
   0.91290112  1.5897487  -0.12848036 -0.02122816]
 [ 0.70416856  0.66051164 -0.67679244  0.06215879  0.3981566   0.05219834
  -0.12492178 -0.76579353  0.47501578  0.0097346 ]
 [ 2.60131454  0.42600993  0.34494364  0.27844126 -0.57624792  1.1052864
  -0.87325887 -1.12422647 -1.08378102  0.54748628]
 [-1.08366506  3.09910153 -1.48910813 -0.70931297  1.16902872  1.09815303
  -0.21802266 -0.75579485  0.90219077 -0.27051459]
 [-0.12054961  0.03778575  0.28789717  0.75125472  1.78099942 -0.75755401
   1.42772162 -1.4783212   0.48985041 -0.57518843]
 [ 1.93375055 -0.96123576 -1.09313051 -0.33863098  1.19346663 -0.53262519
   0.6647377  -0.06762417  2.21499813  0.08426419]
 [ 0.86391664  0.91681879  0.4608687   1.0523493  -0.2799211  -0.01627756
  -0.15167148 -0.53503426  0.4586827  -1.09020846]
 [-0.49299941  0.87760694 -1.02554443 -0.40998378 -0.67015641  0.35995216
   1.28482575 -1.91248485 -1.22325049  0.81654871]
 [-0.29775753 -0.47499429 -1.47616956 -1.50531261  0.14200872  0.96804507
   0.25396711 -0.34629848  0.42063896  0.72427493]
 [-0.75483827 -1.07676166  0.25295788  1.12052619 -0.09102472 -0.03467146
   1.39762496 -0.73961535 -0.19335656 -1.58354179]
 [ 0.23776086 -0.80124875 -0.77459659  0.64633365  0.75243249 -0.53485725
   0.95950388 -0.33768456 -0.29536033 -0.10107084]
 [ 0.71297423  0.70184209  0.13979925  1.57616535  0.02975748  0.80530787
  -0.00386501 -1.32944099  0.59590004  1.36398646]
 [ 1.31237322  0.03859897 -0.79316176  0.35538693 -2.09147822 -1.47583403
   0.26216234  1.84488153  0.60323907 -1.31696376]
 [-1.6544636  -0.22013947 -0.53987893 -1.26108709 -1.52094698  0.15431567
   1.15578321 -0.24931426 -1.51635808  0.20172083]
 [ 0.49426606 -1.47981591  0.37186757 -0.393172   -0.72852066 -0.83644467
   1.21245927 -0.07464727 -0.02810124 -0.78931021]
 [-0.39980288  1.6930363   0.37400399 -0.18776194 -0.40272651 -1.66722774
   0.92021234 -0.28110006  0.03671571  0.12358258]
 [-1.54129047 -0.31956192  0.147291    0.26846019  1.81851954 -0.44708236
   0.72280804  2.22559664  0.36395371  1.76529549]
 [-0.82929502 -0.24993208  0.68641811  0.75025269  0.55547807 -1.02916928
   0.35421469 -0.09006218 -0.32778189  0.05587445]
 [-1.21709911  0.89075841 -0.75140369 -0.37166205 -0.48601786 -0.13091902
  -0.64456205  0.59523479 -1.37414605 -1.28915239]
 [ 0.24932206  1.3023043  -0.62293976  0.470793   -1.27778476 -0.34282028
   1.79511294  0.747908    1.79217398 -1.08031729]
 [ 0.58553802  0.04599498  0.86208879  0.57595296 -0.94993146 -0.72540878
   0.01874102 -0.86395297 -0.27653266  1.1339044 ]
 [ 1.86190929 -0.33231426  0.45892998 -0.04735414  0.94912272  0.53163057
   1.94085143  1.61822237 -0.22814271  1.18695972]
 [ 0.47889835 -0.6396666  -0.40302427  0.83406939 -1.106254    0.89382704
  -0.29149097  0.36674313 -1.16749842  1.62534013]
 [ 0.3913334  -0.2814333   0.43561312  0.46164929  1.30238714  1.74231653
  -1.18765091 -0.5038297  -0.96581872  0.536273  ]
 [-0.22585647  1.40070367  0.08835178 -1.29164483  0.92023832 -0.52202311
   0.10014648 -1.23436176  0.25758041  0.36149703]
 [ 0.05966304 -0.40160992 -0.2822925  -0.5997544   0.27503194  0.92070711
  -0.9507132   0.65186006 -0.13445905  0.63542627]
 [ 0.03323966  1.19369234  0.65600219  0.00635295  0.44729854  2.10828574
  -0.91264592 -0.38619523 -1.42590564  1.36782754]
 [-0.61962781 -0.5317619  -0.73943558  0.36521739  1.18797179 -0.1629731
  -1.04128241 -0.97709681  1.20020229 -0.24344262]
 [ 1.03707452  1.05794622  1.22027381  0.26988928 -0.81611332 -0.35750843
  -0.14609356  0.12356533  1.44314176 -0.57639495]
 [ 0.05164345  0.01902998  0.37958624  0.00898432  0.43386635 -1.67593319
   1.63883535 -0.48593203  0.28344493 -0.21567783]
 [-0.6157818  -0.16981992 -0.97438595 -0.50188839  0.42141657 -1.32560711
   1.74810136  0.27974077 -0.29862478  0.16439222]]

array([[ 0.99949988,  1.48059584, -1.02451155, -0.8614114 , -0.27996923,
        -2.85507207,  0.1047417 ,  1.1344126 , -0.31293796, -0.34346681],
       [-1.20196757, -0.02035361, -0.5311331 , -0.22103344, -0.41925933,
         0.89302975,  0.90020952,  0.27964719,  0.26177091, -0.67754126]])

In [101]:
np.random.seed(42)
arr_r=np.random.normal(0,1,100).reshape(-1,10)
arr_r2=np.random.normal(0,1,100).reshape(-1,10)

#o [:2] MOSTRA QUE QUERO INDEXAR DO INICIO DO OBJ ATÉ A LINHA 1 (IGNORA O 2), PRA TODAS AS COLUNAS PQ NAO COLOQUEI NENHUMA ALI
#ISSO NAO FUNCIONA PRO CONTRARIO
arr_r[:2]

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
        -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
        -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ]])

In [102]:
pd.DataFrame(arr_r) <= pd.DataFrame(arr_r2)

       0      1      2      3      4      5      6      7      8      9
0  False  False  False  False   True   True   True  False   True  False
1  False   True  False   True   True   True   True  False   True   True
2  False  False   True   True   True   True   True  False   True  False
3  False  False  False   True  False   True  False   True   True  False
4  False   True  False   True   True   True  False  False   True   True
5  False   True  False  False  False  False   True   True  False  False
6  False   True   True   True   True  False   True   True  False  False
7  False  False  False  False   True   True  False   True  False   True
8   True  False  False   True   True   True  False  False  False  False
9  False  False   True  False   True   True  False  False   True  False

In [105]:
df1=pd.DataFrame(arr_r) 
df2=pd.DataFrame(arr_r2)
display(df1.head())

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
2,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694
3,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,-1.959670,-1.328186,0.196861
4,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040

In [108]:
1==1 and 1==3 or 1==1

True

In [107]:
print(1 in [1,2,3])
'1' in [1,2,3]

True

False

In [ ]:
p=1
q=1.0
p is q #também observa classe

False