# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [2]:
a = 2.0 + 3.0 / 5.0 == 10
a

False

In [3]:
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
b

True

In [4]:
c = 10 <= a / b + 33.8 < 100
c

True

In [5]:
d = 5 != a / (b + c)
d

True

In [6]:
e = 33 == d * 2
e

False

## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [7]:
print(('a',1,True,'b',0,False) == ('a',True,1,'b',False,0))
print(['a',1,True,'b',0,False] == ('a',True,1,'b',False,0))
print(['a',1,True,'b',0,False] == ['a',True,1,'b',False,0])
print(['a',1,True,'b',0,False] < ['a',True,1])
print(['a',1,True,'b',0,False] != 1)
print(['a',True,1] <= ['a',True,1] == ['a',1,True,'b',0,False])

True
False
True
False
True
False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [8]:
import pandas as pd

In [9]:
# importar novamente ajustando o index
df8_3 = pd.read_csv("df_10_lista7.csv", index_col="Unnamed: 0").round(3)

print(df8_3)

                    0      1       2      3  media_linhas
0               2.600  2.800  34.729  0.069        10.050
1               0.139  1.612   1.673  5.893         2.329
2               0.263  0.372   2.600  2.800         1.509
3              34.729  0.069   0.139  1.612         9.137
4               1.673  5.893   0.263  0.372         2.050
media_colunas   7.881  2.149   7.881  2.149         5.015

## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [10]:
df8_3.shape

(6, 5)

In [11]:
import numpy as np

In [12]:
arr8_3=np.ones_like(df8_3)
arr8_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [13]:
#para observar de forma visual a comparação:
#df8_3.values==arr8_3 ou:
df8_3==arr8_3

                   0      1      2      3  media_linhas
0              False  False  False  False         False
1              False  False  False  False         False
2              False  False  False  False         False
3              False  False  False  False         False
4              False  False  False  False         False
media_colunas  False  False  False  False         False

In [14]:
#Para contar o número de valores iguais:
print(f'Número de valores iguais no array e na dataframe: {np.sum(df8_3.values==arr8_3)}')

Número de valores iguais no array e na dataframe: 0

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [48]:
print(f'Número de valores do dataframe superiores aos do array: {np.sum(df8_3.values>arr8_3)}')
#apenas a título de verificação visual:
df8_3>arr8_3

Número de valores do dataframe superiores aos do array: 22

                   0      1      2      3  media_linhas
0               True   True   True  False          True
1              False   True   True   True          True
2              False  False   True   True          True
3               True  False  False   True          True
4               True   True  False  False          True
media_colunas   True   True   True   True          True

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [46]:
print(f'Número de valores do dataframe iguais ou inferiores aos do array: {np.sum(df8_3.values<=arr8_3)}')
#apenas a título de verificação visual:
df8_3<=arr8_3

Número de valores do dataframe iguais ou inferiores aos do array: 8

                   0      1      2      3  media_linhas
0              False  False  False   True         False
1               True  False  False  False         False
2               True   True  False  False         False
3              False   True   True  False         False
4              False  False   True   True         False
media_colunas  False  False  False  False         False

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [49]:
print(f'Quantidade de valores na df entre 0 e 1, excluindo 0 e 1: {((0<df8_3) & (df8_3<1)).values.sum()}')
#apenas a título de verificação visual:
((0<df8_3) & (df8_3<1)).values

Quantidade de valores na df entre 0 e 1, excluindo 0 e 1: 8

array([[False, False, False,  True, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [False,  True,  True, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False]])

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [60]:
coluna_medias_linhas = list(df8_3.iloc[:,4])
quantidade = 0
for x in coluna_medias_linhas:
    if x <= 5:
        quantidade += 1
quantidade

3

In [62]:
#alternativa para usar o count, sem indexar objeto:
[x <= 5 for x in coluna_medias_linhas].count(True)

3

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [63]:
quantidade2 = 0
for x in coluna_medias_linhas:
    if x > 5:
        quantidade2 += 1
quantidade2

3